### ISSUE TITLE
Bitdefender hate Mercury

### ISSUE THREAD

**Issue by Makazzz** [sp0ok3r/Mercury#2]
Each time I extract the MercuryBOT.exe Bitdefender Total Security remove it or block it forever. And even put it in the exclusion list dosn't work. I have to desactivate the whole Antivirus for extracting it. (Gen:Variant.MSILPerseus.185495). And the VirusTotal is pretty terrifying... https://www.virustotal.com/gui/file/a49051926b6c5e6d8744c1b6b7f6df01228e3d60250f3030ef78717c950d8e56/detection

**Comment by sp0ok3r** [comment]
all false positives.
