### ISSUE TITLE
Can you share php?

### ISSUE THREAD

**Issue by mrranger** [sp0ok3r/Mercury#3]
Can you share php?

**Comment by sp0ok3r** [comment]
What?, im not using php

**Comment by mrranger** [comment]
http://sp0ok3r.tk/Mercury/update-changelog.php
http://sp0ok3r.tk/Mercury/update.php

I can’t understand what settings need to be changed so that everything works


Only check for updates after 14 days
Change Settings file if any error appears

**Comment by mrranger** [comment]
MercuryBOT.User2Json.MercurySettings.LastTimeCheckedUpdate.get returned null.

**Comment by mrranger** [comment]
System.Collections.Generic.KeyNotFoundException: "The given key was not present."

**Comment by sp0ok3r** [comment]
add me on steam https://steamcommunity.com/id/sp0ok3rz/
