### ISSUE TITLE
A question

### ISSUE THREAD

**Issue by RadicalRedemption** [sp0ok3r/Mercury#4]
Is it possible to add accounts from username:password style?

**Comment by sp0ok3r** [comment]
No,but I can try to implement this.

**Comment by RadicalRedemption** [comment]
Is it also possible to disable automatically adding detected accounts on the PC?

**Comment by RadicalRedemption** [comment]
And the program also crashes on my PC.

**Comment by RadicalRedemption** [comment]
Wait, i thought you could idle multiple accounts at the same time..

**Comment by sp0ok3r** [comment]
add me https://steamcommunity.com/id/sp0ok3rz/
