### ISSUE TITLE
Idle suggestion

### ISSUE THREAD

**Issue by ForGamezCZ** [sp0ok3r/Mercury#7]
- Add auto-login (so it logs you to specific account after startup).
- Add idle on login (saves time).
- Allow 33 games to be idled instead of 32 (as far as I know you can idle 33 games, not just 32).

Note: This is suggestion but idk how to label it.

**Comment by sp0ok3r** [comment]
You can already auto-login if you click on EDIT ACCOUNT
I will try to add this
I will test this

**Comment by ForGamezCZ** [comment]
Ah I see, thank you!
