### ISSUE TITLE
MercuryBOT Doesn't start

### ISSUE THREAD

**Issue by GustavRaispits** [sp0ok3r/Mercury#8]
Tested on Windows 11:
![report](https://user-images.githubusercontent.com/34628862/155841092-488cf235-f77f-41d2-93f7-efa777f3a561.gif)

I've also tested the program on Windows 10 and Windows 7, the same problem is occured.

- Not an Antivirus problem 
- .NET Framework is installed correctly
- C++ Package is installed

**Comment by sp0ok3r** [comment]
https://github.com/sp0ok3r/Mercury/releases/tag/4.0.0-beta6.4b download again and try

**Comment by sp0ok3r** [comment]
fixed
